### ISSUE TITLE
Could you clarify where the finetune.py file is located in the demo for dropbp.sh

### ISSUE THREAD

**Issue by p81sunshine** [WooSunghyeon/dropbp#2]
I understand that the finetune.py file cannot be released due to licensing reasons. Could you provide a link to access it or any related resources? Thank you !

**Comment by WooSunghyeon** [comment]
I’m sorry for the late reply.

We applied our DropBP method by modifying the code provided in the supplementary materials of the VeRA paper ([Link](https://openreview.net/forum?id=NjNfLdxr3A)). Specifically, we utilized the `instruct/finetune.py` file from the included zip archive and removed unnecessary VeRA-related configurations (e.g., `init_type`, `d_init_type`, `dynamic_uv`, `shared_dim`, `shared_uv`). We then added the `drop_rate` parameter to the `Trainer` as described in the `dropbp/huggingface/README.md`.

If you have any further questions, feel free to ask.
